# .github/workflows/deploy-to-domestic.yml
name: Deploy to Domestic Server

on:
  # Trigger the workflow on push events to the main branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Ensure this matches your project's requirement

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install # Or 'yarn install' if you use Yarn

      # 4. Build the static site
      - name: Build static files
        run: npm run export
        env:
          # This environment variable is crucial for the static export build
          EXPORT: true

      # 5. Deploy files to server with rsync
      - name: Deploy to server with rsync
        uses: easing-themes/rsync-deploy@v2.2.1
        with:
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "out/"
          TARGET: ${{ secrets.REMOTE_TARGET_DIR }}
          ARGS: "-avz --delete"